// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBYHW85wZrvfOuriCq5zatLwypkZLzYPs',
    appId: '1:674890052377:web:49c9ae41a34d31ec6a4b88',
    messagingSenderId: '674890052377',
    projectId: 'paginate-firebase-example',
    authDomain: 'paginate-firebase-example.firebaseapp.com',
    storageBucket: 'paginate-firebase-example.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7uXts8G2FbAIaqte-9kymh81_SQP3PZE',
    appId: '1:674890052377:android:4a76f58682589db86a4b88',
    messagingSenderId: '674890052377',
    projectId: 'paginate-firebase-example',
    storageBucket: 'paginate-firebase-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB42oHXDSjz27yo47c-B6tcXWoGXyG1SR4',
    appId: '1:674890052377:ios:788fd776fe9b57976a4b88',
    messagingSenderId: '674890052377',
    projectId: 'paginate-firebase-example',
    storageBucket: 'paginate-firebase-example.appspot.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB42oHXDSjz27yo47c-B6tcXWoGXyG1SR4',
    appId: '1:674890052377:ios:8e4f2531d54c310c6a4b88',
    messagingSenderId: '674890052377',
    projectId: 'paginate-firebase-example',
    storageBucket: 'paginate-firebase-example.appspot.com',
    iosBundleId: 'space.cogitare.example',
  );
}
